# frontend/cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/cinefinder-frontend:latest',
      '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/cinefinder-frontend:latest'